#
# Makefile for the input misc STM imu lsm6dl0 driver
#
lsm6dl0-core-y += lsm6dl0_core.o
obj-$(CONFIG_INPUT_LSM6DL0) += lsm6dl0-core.o
obj-$(CONFIG_INPUT_LSM6DL0_I2C) += lsm6dl0_i2c.o
obj-$(CONFIG_INPUT_LSM6DL0_SPI) += lsm6dl0_spi.o
