#
# Makefile for the input misc lps22hh driver.
#

lps22hh-core-y += lps22hh_core.o
obj-$(CONFIG_INPUT_LPS22HH) += lps22hh-core.o
obj-$(CONFIG_INPUT_LPS22HH_I2C) += lps22hh_i2c.o
obj-$(CONFIG_INPUT_LPS22HH_SPI) += lps22hh_spi.o
