#
# Makefile for the input misc STM acc ais3624dq driver
#
obj-$(CONFIG_INPUT_AIS3624DQ) += ais3624dq_acc.o
obj-$(CONFIG_INPUT_AIS3624DQ_I2C) += ais3624dq_i2c.o
obj-$(CONFIG_INPUT_AIS3624DQ_SPI) += ais3624dq_spi.o
