#
# Makefile for the input misc STM acc lis3dh driver
#
lis3dh-core-y += lis3dh_core.o
obj-$(CONFIG_INPUT_LIS3DH) += lis3dh-core.o
obj-$(CONFIG_INPUT_LIS3DH_I2C) += lis3dh_i2c.o
obj-$(CONFIG_INPUT_LIS3DH_SPI) += lis3dh_spi.o
