#
# Makefile for the input misc STM imu ism330dlc driver
#
ism330dlc-core-y += ism330dlc_core.o
obj-$(CONFIG_INPUT_ISM330DLC) += ism330dlc-core.o
obj-$(CONFIG_INPUT_ISM330DLC_I2C) += ism330dlc_i2c.o
obj-$(CONFIG_INPUT_ISM330DLC_SPI) += ism330dlc_spi.o
