obj-$(CONFIG_INPUT_ISM303DAC) += ism303dac_acc.o ism303dac_mag.o ism303dac_core.o
obj-$(CONFIG_INPUT_ISM303DAC_I2C) += ism303dac_acc_i2c.o ism303dac_mag_i2c.o
obj-$(CONFIG_INPUT_ISM303DAC_SPI) += ism303dac_acc_spi.o ism303dac_mag_spi.o
