#
# Makefile for the input misc STM acc h3lis331dl driver
#
h3lis331dl-core-y += h3lis331dl_core.o
obj-$(CONFIG_INPUT_H3LIS331DL) += h3lis331dl-core.o
obj-$(CONFIG_INPUT_H3LIS331DL_I2C) += h3lis331dl_i2c.o
obj-$(CONFIG_INPUT_H3LIS331DL_SPI) += h3lis331dl_spi.o
