#
# Makefile for the input misc STM acc lis2dw12 driver
#
lis2dw12-core-y += lis2dw12_core.o
obj-$(CONFIG_INPUT_LIS2DW12) += lis2dw12-core.o
obj-$(CONFIG_INPUT_LIS2DW12_I2C) += lis2dw12_i2c.o
obj-$(CONFIG_INPUT_LIS2DW12_SPI) += lis2dw12_spi.o
