#
# Makefile for the input misc lsm303d driver.
#

# Each configuration option enables a list of files.

lsm303d-y += lsm303d_core.o
obj-$(CONFIG_INPUT_LSM303D) += lsm303d.o
obj-$(CONFIG_INPUT_LSM303D_I2C) += lsm303d_i2c.o
obj-$(CONFIG_INPUT_LSM303D_SPI) += lsm303d_spi.o
