#
# Makefile for the input misc STM gyro drivers.
#

obj-$(CONFIG_INPUT_L3G4200D) += l3g4200d/
obj-$(CONFIG_INPUT_L3GD20) += l3gd20/
obj-$(CONFIG_INPUT_L3GD20H) += l3gd20h/
obj-$(CONFIG_INPUT_A3G4250D) += a3g4250d/
