#
# Makefile for the input misc STM acc lis2dh driver
#
lis2dh-acc-y += lis2dh_acc.o
obj-$(CONFIG_INPUT_LIS2DH) += lis2dh-acc.o
obj-$(CONFIG_INPUT_LIS2DH_I2C) += lis2dh_i2c.o
obj-$(CONFIG_INPUT_LIS2DH_SPI) += lis2dh_spi.o
