#
# Makefile for the input misc STM imu lsm330dlc driver
#
obj-$(CONFIG_INPUT_LSM330DLC) += lsm330dlc_acc.o lsm330dlc_gyr.o
obj-$(CONFIG_INPUT_LSM330DLC_I2C) += lsm330dlc_acc_i2c.o lsm330dlc_gyr_i2c.o
obj-$(CONFIG_INPUT_LSM330DLC_SPI) += lsm330dlc_acc_spi.o lsm330dlc_gyr_spi.o

# ccflags-y += -DLSM330DLC_DEBUG
