#
# Makefile for the input misc hts221 driver.
#

hts221-y += hts221_core.o
obj-$(CONFIG_INPUT_HTS221) += hts221.o
obj-$(CONFIG_INPUT_HTS221_I2C) += hts221_i2c.o
obj-$(CONFIG_INPUT_HTS221_SPI) += hts221_spi.o

# ccflags-y += -DHTS221_DEBUG
