#
# Makefile for the input misc STM UV uvis25 driver
#
uvis25-core-y += uvis25_core.o
obj-$(CONFIG_INPUT_UVIS25) += uvis25-core.o
obj-$(CONFIG_INPUT_UVIS25_I2C) += uvis25_i2c.o
obj-$(CONFIG_INPUT_UVIS25_SPI) += uvis25_spi.o
