#
# Makefile for the input misc l3gd20 driver.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_INPUT_L3GD20) += l3gd20_gyr.o
obj-$(CONFIG_INPUT_L3GD20_I2C) += l3gd20_gyr_i2c.o
obj-$(CONFIG_INPUT_L3GD20_SPI) += l3gd20_gyr_spi.o

# ccflags-y += -DL3GD20_DEBUG
