#
# Makefile for the input misc lis3mdl driver.
#

# Each configuration option enables a list of files.

lis3mdl-y += lis3mdl_mag.o
obj-$(CONFIG_INPUT_LIS3MDL) += lis3mdl.o
obj-$(CONFIG_INPUT_LIS3MDL_I2C) += lis3mdl_i2c.o
obj-$(CONFIG_INPUT_LIS3MDL_SPI) += lis3mdl_spi.o

# ccflags-y += -DLIS3MDL_DEBUG
