#
# Makefile for the input misc STM imu asm330lxh driver
#
obj-$(CONFIG_INPUT_ASM330LXH) += asm330lxh.o
obj-$(CONFIG_INPUT_ASM330LXH_I2C) += asm330lxh_i2c.o
obj-$(CONFIG_INPUT_ASM330LXH_SPI) += asm330lxh_spi.o
