#
# Makefile for the input misc STM acc lis2hh12 driver
#
lis2hh12-core-y += lis2hh12_core.o
obj-$(CONFIG_INPUT_LIS2HH12) += lis2hh12-core.o
obj-$(CONFIG_INPUT_LIS2HH12_I2C) += lis2hh12_i2c.o
obj-$(CONFIG_INPUT_LIS2HH12_SPI) += lis2hh12_spi.o
