#
# Makefile for the input misc lsm303c driver.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_INPUT_LSM303C) += lsm303c_acc.o lsm303c_mag.o
obj-$(CONFIG_INPUT_LSM303C_I2C) += lsm303c_acc_i2c.o lsm303c_mag_i2c.o
obj-$(CONFIG_INPUT_LSM303C_SPI) += lsm303c_acc_spi.o lsm303c_mag_spi.o
