#
# Makefile for the input misc STM acc lis2de driver
#
obj-$(CONFIG_INPUT_AIS328DQ) += ais328dq_acc.o
obj-$(CONFIG_INPUT_AIS328DQ_I2C) += ais328dq_i2c.o
obj-$(CONFIG_INPUT_AIS328DQ_SPI) += ais328dq_spi.o
