#
# Makefile for the input misc lps33hw and lps35hw driver.
#

lps33hw-core-y += lps33hw_core.o
obj-$(CONFIG_INPUT_LPS33HW) += lps33hw-core.o
obj-$(CONFIG_INPUT_LPS33HW_I2C) += lps33hw_i2c.o
obj-$(CONFIG_INPUT_LPS33HW_SPI) += lps33hw_spi.o
