#
# Makefile for the input misc STM imu lsm9ds0 driver
#
obj-$(CONFIG_INPUT_LSM9DS0) += lsm9ds0_gyr.o lsm9ds0_acc_mag.o
obj-$(CONFIG_INPUT_LSM9DS0_I2C) += lsm9ds0_gyr_i2c.o lsm9ds0_acc_mag_i2c.o
obj-$(CONFIG_INPUT_LSM9DS0_SPI) += lsm9ds0_gyr_spi.o lsm9ds0_acc_mag_spi.o

# ccflags-y += -DLSM9DS0_DEBUG
