#
# Makefile for the input misc STM acc lps25h driver
#
lps25h-core-y += lps25h_core.o
obj-$(CONFIG_INPUT_LPS25H) += lps25h-core.o
obj-$(CONFIG_INPUT_LPS25H_I2C) += lps25h_i2c.o
obj-$(CONFIG_INPUT_LPS25H_SPI) += lps25h_spi.o
