#
# Makefile for the input misc STM acc lis3de driver
#
lis3de-core-y += lis3de_core.o
obj-$(CONFIG_INPUT_LIS3DE) += lis3de-core.o
obj-$(CONFIG_INPUT_LIS3DE_I2C) += lis3de_i2c.o
obj-$(CONFIG_INPUT_LIS3DE_SPI) += lis3de_spi.o
