#
# Makefile for the input misc STM acc lis3dsh driver
#
lis3dsh-core-y += lis3dsh_core.o
obj-$(CONFIG_INPUT_LIS3DSH) += lis3dsh-core.o
obj-$(CONFIG_INPUT_LIS3DSH_I2C) += lis3dsh_i2c.o
obj-$(CONFIG_INPUT_LIS3DSH_SPI) += lis3dsh_spi.o
