#
# Makefile for the input misc STM acc l3g4200d driver
#
l3g4200d-core-y += l3g4200d_core.o
obj-$(CONFIG_INPUT_L3G4200D) += l3g4200d-core.o
obj-$(CONFIG_INPUT_L3G4200D_I2C) += l3g4200d_i2c.o
obj-$(CONFIG_INPUT_L3G4200D_SPI) += l3g4200d_spi.o
