#
# Makefile for the input misc STM imu lsm6dsl driver
#
lsm6dsl-core-y += lsm6dsl_core.o
obj-$(CONFIG_INPUT_LSM6DSL) += lsm6dsl-core.o
obj-$(CONFIG_INPUT_LSM6DSL_I2C) += lsm6dsl_i2c.o
obj-$(CONFIG_INPUT_LSM6DSL_SPI) += lsm6dsl_spi.o
