#
# Makefile for the input misc STM imu lsm6dsm driver
#
lsm6dsm-core-y += lsm6dsm_core.o
obj-$(CONFIG_INPUT_LSM6DSM) += lsm6dsm-core.o
obj-$(CONFIG_INPUT_LSM6DSM_I2C) += lsm6dsm_i2c.o
obj-$(CONFIG_INPUT_LSM6DSM_SPI) += lsm6dsm_spi.o
