#
# Makefile for the input misc STM acc lis331dlh driver
#
lis331dlh-core-y += lis331dlh_core.o
obj-$(CONFIG_INPUT_LIS331DLH) += lis331dlh-core.o
obj-$(CONFIG_INPUT_LIS331DLH_I2C) += lis331dlh_i2c.o
obj-$(CONFIG_INPUT_LIS331DLH_SPI) += lis331dlh_spi.o
