#
# Makefile for the input misc STM acc drivers.
#

obj-$(CONFIG_INPUT_AIS328DQ) += ais328dq/
obj-$(CONFIG_INPUT_AIS3624DQ) += ais3624dq/
obj-$(CONFIG_INPUT_LIS2DH) += lis2dh/
obj-$(CONFIG_INPUT_LIS2DE) += lis2de/
obj-$(CONFIG_INPUT_LIS2DS) += lis2ds/
obj-$(CONFIG_INPUT_H3LIS100DL) += h3lis100dl/
obj-$(CONFIG_INPUT_LIS3DSH) += lis3dsh/
obj-$(CONFIG_INPUT_LIS2HH12) += lis2hh12/
obj-$(CONFIG_INPUT_LIS3DE) += lis3de/
obj-$(CONFIG_INPUT_LIS331DLH) += lis331dlh/
obj-$(CONFIG_INPUT_LIS331HH) += lis331hh/
obj-$(CONFIG_INPUT_H3LIS331DL) += h3lis331dl/
obj-$(CONFIG_INPUT_LIS3DH) += lis3dh/
obj-$(CONFIG_INPUT_LIS2DW12) += lis2dw12/
