#
# Makefile for the input misc STM imu lsm9ds1 driver
#
obj-$(CONFIG_INPUT_LSM9DS1) += lsm9ds1_mag.o lsm9ds1_acc_gyr.o
obj-$(CONFIG_INPUT_LSM9DS1_I2C) += lsm9ds1_mag_i2c.o lsm9ds1_acc_gyr_i2c.o
obj-$(CONFIG_INPUT_LSM9DS1_SPI) += lsm9ds1_mag_spi.o lsm9ds1_acc_gyr_spi.o

# ccflags-y += -DLSM9DS1_DEBUG
