obj-$(CONFIG_INPUT_LSM303AH) += lsm303ah_acc.o lsm303ah_mag.o lsm303ah_core.o
obj-$(CONFIG_INPUT_LSM303AH_I2C) += lsm303ah_acc_i2c.o lsm303ah_mag_i2c.o
obj-$(CONFIG_INPUT_LSM303AH_SPI) += lsm303ah_acc_spi.o lsm303ah_mag_spi.o
