#
# Makefile for the input misc STM imu lsm6ds3 driver
#
lsm6ds3-core-y += lsm6ds3_core.o
obj-$(CONFIG_INPUT_LSM6DS3) += lsm6ds3-core.o
obj-$(CONFIG_INPUT_LSM6DS3_I2C) += lsm6ds3_i2c.o
obj-$(CONFIG_INPUT_LSM6DS3_SPI) += lsm6ds3_spi.o
