#
# Makefile for the input misc STM acc h3lis100dl driver
#
h3lis100dl-core-y += h3lis100dl_core.o
obj-$(CONFIG_INPUT_H3LIS100DL) += h3lis100dl-core.o
obj-$(CONFIG_INPUT_H3LIS100DL_I2C) += h3lis100dl_i2c.o
obj-$(CONFIG_INPUT_H3LIS100DL_SPI) += h3lis100dl_spi.o
