#
# Makefile for the input misc STM imu asm330lhh driver
#
asm330lhh-core-y += asm330lhh_core.o
obj-$(CONFIG_INPUT_ASM330LHH) += asm330lhh-core.o
obj-$(CONFIG_INPUT_ASM330LHH_I2C) += asm330lhh_i2c.o
obj-$(CONFIG_INPUT_ASM330LHH_SPI) += asm330lhh_spi.o
