#
# Makefile for the input misc STM acc lis2de driver
#
lis2de-acc-y += lis2de_acc.o
obj-$(CONFIG_INPUT_LIS2DE) += lis2de-acc.o
obj-$(CONFIG_INPUT_LIS2DE_I2C) += lis2de_i2c.o
obj-$(CONFIG_INPUT_LIS2DE_SPI) += lis2de_spi.o
