#
# Makefile for the input misc STM imu lsm6dsox driver
#
lsm6dsox-core-y += lsm6dsox_core.o
obj-$(CONFIG_INPUT_LSM6DSOX) += lsm6dsox-core.o
obj-$(CONFIG_INPUT_LSM6DSOX_I2C) += lsm6dsox_i2c.o
obj-$(CONFIG_INPUT_LSM6DSOX_SPI) += lsm6dsox_spi.o
