#
# Makefile for the input misc lps22df driver.
#

lps22df-core-y += lps22df_core.o
obj-$(CONFIG_INPUT_LPS22DF) += lps22df-core.o
obj-$(CONFIG_INPUT_LPS22DF_I2C) += lps22df_i2c.o
obj-$(CONFIG_INPUT_LPS22DF_SPI) += lps22df_spi.o
