#
# Makefile for the input misc STM acc a3g4250d driver
#
a3g4250d-core-y += a3g4250d_core.o
obj-$(CONFIG_INPUT_A3G4250D) += a3g4250d-core.o
obj-$(CONFIG_INPUT_A3G4250D_I2C) += a3g4250d_i2c.o
obj-$(CONFIG_INPUT_A3G4250D_SPI) += a3g4250d_spi.o
