#
# Makefile for the input misc STM imu drivers.
#

obj-$(CONFIG_INPUT_LSM6DS3) += lsm6ds3/
obj-$(CONFIG_INPUT_LSM6DSM) += lsm6dsm/
obj-$(CONFIG_INPUT_LSM6DSL) += lsm6dsl/
obj-$(CONFIG_INPUT_LSM9DS0) += lsm9ds0/
obj-$(CONFIG_INPUT_LSM9DS1) += lsm9ds1/
obj-$(CONFIG_INPUT_LSM330DLC) += lsm330dlc/
obj-$(CONFIG_INPUT_LSM6DS0) += lsm6ds0/
obj-$(CONFIG_INPUT_LSM330) += lsm330/
obj-$(CONFIG_INPUT_ISM330DLC) += ism330dlc/
obj-$(CONFIG_INPUT_ASM330LHH) += asm330lhh/
obj-$(CONFIG_INPUT_LSM6DSOX) += lsm6dsox/
