#
# Makefile for the input misc lsm303dlhc driver.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_INPUT_LSM303DLHC) += lsm303dlhc_acc.o lsm303dlhc_mag.o
obj-$(CONFIG_INPUT_LSM303DLHC_I2C) += lsm303dlhc_acc_i2c.o lsm303dlhc_mag_i2c.o
