#
# Makefile for the input misc STM acc lis331hh driver
#
lis331hh-core-y += lis331hh_core.o
obj-$(CONFIG_INPUT_LIS331HH) += lis331hh-core.o
obj-$(CONFIG_INPUT_LIS331HH_I2C) += lis331hh_i2c.o
obj-$(CONFIG_INPUT_LIS331HH_SPI) += lis331hh_spi.o
