#
# Makefile for the input misc STM imu lsm6ds0 driver
#
lsm6ds0-core-y += lsm6ds0_core.o
obj-$(CONFIG_INPUT_LSM6DS0) += lsm6ds0-core.o
obj-$(CONFIG_INPUT_LSM6DS0_I2C) += lsm6ds0_i2c.o
obj-$(CONFIG_INPUT_LSM6DS0_SPI) += lsm6ds0_spi.o
