#
# Makefile for the input misc STM acc lis2ds driver
#
lis2ds-core-y += lis2ds_core.o
obj-$(CONFIG_INPUT_LIS2DS) += lis2ds-core.o
obj-$(CONFIG_INPUT_LIS2DS_I2C) += lis2ds_i2c.o
obj-$(CONFIG_INPUT_LIS2DS_SPI) += lis2ds_spi.o
