#
# Makefile for the input misc STM imu lsm330 driver
#
obj-$(CONFIG_INPUT_LSM330) += lsm330_acc.o lsm330_gyr.o
obj-$(CONFIG_INPUT_LSM330_I2C) += lsm330_acc_i2c.o lsm330_gyr_i2c.o
obj-$(CONFIG_INPUT_LSM330_SPI) += lsm330_acc_spi.o lsm330_gyr_spi.o
